/* Pure game rules shared by browser, save validation and tests. */
globalThis.CafeEngine = (() => {
  const D=globalThis.CafeData, themes=['classic','mint','rose','night'];
  const integer=x=>Number.isSafeInteger(x)&&x>=0;
  const index=(x,max)=>integer(x)&&x<max;
  const list=(a,max)=>Array.isArray(a)&&a.length>0&&a.length<=max&&new Set(a).size===a.length&&a.every(x=>index(x,max));
  function valid(s){return !!(s&&(!s.interactionVisit||(Array.isArray(s.interactionVisit)&&s.interactionVisit.length===6&&s.interactionVisit.every(integer)))&&[1,2].includes(s.version)&&['coins','earned','sold','speed','counter','price','serial'].every(k=>integer(s[k]))&&s.speed<=5&&s.counter<=2&&s.price<=5&&list(s.unlocked,D.drinks.length)&&s.unlocked.includes(0)&&Array.isArray(s.decor)&&s.decor.length<=4&&s.decor.includes('classic')&&s.decor.every(x=>themes.includes(x))&&s.decor.includes(s.theme)&&s.friend?.length===6&&s.friend.every(integer)&&Array.isArray(s.orders)&&s.orders.length===3&&new Set(s.orders.map(o=>o.id)).size===3&&s.orders.every(o=>integer(o.id)&&index(o.member,6)&&s.unlocked.includes(o.drink)&&integer(o.start)&&integer(o.end)&&o.end>=o.start&&(o.dessert==null||(s.desserts?.includes(o.dessert)&&index(o.dessert,D.desserts.length))))&&(s.version===1||(list(s.desserts,D.desserts.length)&&s.desserts.includes(0)&&[0,1,2].every(i=>s.unlocked.includes(i))&&s.talks?.length===6&&s.talks.every(integer))));}
  function newOrder(s,rng=Math.random){const used=s.orders.map(o=>o.member);let member=s.serial%6;for(let n=0;n<6&&used.includes(member);n++)member=(member+1)%6;const sequence=s.serial++;const drink=sequence<3?sequence:s.unlocked[Math.floor(rng()*s.unlocked.length)];const dessert=(sequence%3===2||rng()<.25)?s.desserts[Math.floor(rng()*s.desserts.length)]:null;return {id:s.serial,member,drink,dessert,start:0,end:0};}
  function makeState(){const s={version:2,coins:80,earned:0,sold:0,speed:0,counter:0,price:0,unlocked:[0,1,2],desserts:[0],decor:['classic'],theme:'classic',friend:[0,0,0,0,0,0],talks:[0,0,0,0,0,0],orders:[],serial:0};for(let n=0;n<3;n++)s.orders.push(newOrder(s,()=>.5));return s;}
  function migrate(raw){if(!raw)return {state:makeState(),refund:0,changed:true};if(!valid(raw))throw Error('Invalid save');const s=JSON.parse(JSON.stringify(raw));let refund=0;if(s.version===1){refund=(s.unlocked.includes(1)?100:0)+(s.unlocked.includes(2)?220:0);s.coins+=refund;s.unlocked=[...new Set([0,1,2,...s.unlocked])];s.desserts=[0];s.talks=[0,0,0,0,0,0];s.orders=s.orders.map(o=>({...o,dessert:o.dessert??null}));s.version=2;}return {state:s,refund,changed:raw.version!==2};}
  const speedFactor=s=>Math.pow(.85,s.speed);
  const duration=(s,o)=>Math.round((D.drinks[o.drink][4]+(o.dessert==null?0:D.desserts[o.dessert][4]))*1000*speedFactor(s));
  const payout=(s,o)=>Math.round((D.drinks[o.drink][3]+(o.dessert==null?0:D.desserts[o.dessert][3]))*(1+s.price*.1))+[0,3,6,10][themes.indexOf(s.theme)];
  const cost=(s,k)=>k==='speed'?Math.round(100*Math.pow(1.8,s.speed)):k==='counter'?200*Math.pow(3,s.counter):Math.round(120*Math.pow(1.85,s.price));
  function order(s,id,now=Date.now()){const o=s.orders.find(x=>x.id===id);if(!o)return {ok:false};if(o.end&&o.end<=now){const gain=payout(s,o);s.coins+=gain;s.earned+=gain;s.sold++;s.friend[o.member]++;const pos=s.orders.indexOf(o);s.orders.splice(pos,1);const next=newOrder(s);s.orders.splice(pos,0,next);return {ok:true,delivered:true,gain,member:o.member};}if(!o.start&&s.orders.filter(x=>x.end>now).length<s.counter+1){o.start=now;o.end=now+duration(s,o);return {ok:true,delivered:false,member:o.member};}return {ok:false};}
  function upgrade(s,k){if(!['speed','counter','price'].includes(k)||s[k]>=(k==='counter'?2:5)||s.coins<cost(s,k))return false;s.coins-=cost(s,k);s[k]++;return true;}
  function unlock(s,kind,i){if(!['drinks','desserts'].includes(kind))return false;const key=kind==='drinks'?'unlocked':'desserts',items=D[kind];if(!index(i,items.length)||s[key].includes(i)||s.coins<items[i][5])return false;s.coins-=items[i][5];s[key].push(i);return true;}
  function decorate(s,k){const i=themes.indexOf(k);if(i<0)return false;const cost=[0,180,450,850][i];if(!s.decor.includes(k)){if(s.coins<cost)return false;s.coins-=cost;s.decor.push(k);}s.theme=k;return true;}
  return {valid,newOrder,makeState,migrate,duration,payout,cost,order,upgrade,unlock,decorate};
})();
