/* Official YouTube embeds only. No song files are downloaded or redistributed. */
globalThis.CafeRadio=(()=>{
 let language='ko',panel,player=null,apiPromise=null,active=-1,bag=[],playing=false,mode='youtube',localFiles=[],localUrls=[],localBag=[],localIndex=-1,status='radioHint',audio;
 const text=k=>CafeWords[language][k]??k;
 function shuffled(length,previous){const a=Array.from({length},(_,i)=>i);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}if(a.length>1&&a[a.length-1]===previous)[a[0],a[a.length-1]]=[a[a.length-1],a[0]];return a;}
 function init(){if(panel)return;panel=document.getElementById('radio');panel.innerHTML=`<div class="radio-heading"><h3 data-radio-label="radioTitle"></h3><button type="button" class="quiet" id="radio-close">×</button></div><p class="radio-note" data-radio-label="radioHint"></p><div id="radio-player-wrap" class="radio-player"><div id="youtube-player"></div></div><audio id="local-audio" controls hidden></audio><p id="radio-track" class="radio-track"></p><p id="radio-status" class="radio-note" role="status"></p><div class="radio-controls"><button type="button" class="buy" id="radio-next" data-radio-label="shuffle"></button><button type="button" class="quiet" id="radio-pause" data-radio-label="resumeMusic" disabled></button></div><label class="volume-label"><span data-radio-label="volume"></span><input id="radio-volume" type="range" min="0" max="100" value="35"></label><a id="radio-link" target="_blank" rel="noopener" data-radio-label="officialVideo" hidden></a><button type="button" class="quiet" id="radio-official" data-radio-label="officialSource"></button><div class="local-music"><label class="quiet file-label"><span data-radio-label="localMusic"></span><input id="music-files" type="file" accept="audio/mpeg,audio/ogg,audio/wav,audio/mp4,.mp3,.ogg,.wav,.m4a" multiple></label><p class="radio-note" data-radio-label="localMusicHint"></p></div>`;
 audio=document.getElementById('local-audio');audio.volume=.35;audio.addEventListener('ended',nextLocal);audio.addEventListener('play',()=>{playing=true;status='musicPlaying';paint();});audio.addEventListener('pause',()=>{playing=false;status='musicPaused';paint();});audio.addEventListener('error',()=>{status='musicError';paint();});
 document.getElementById('radio-close').onclick=()=>{if(player?.stopVideo)player.stopVideo();audio.pause();panel.hidden=true;playing=false;};
 document.getElementById('radio-official').onclick=nextOfficial;
 document.getElementById('radio-next').onclick=()=>{if(mode==='local'&&localFiles.length)nextLocal();else nextOfficial();};
 document.getElementById('radio-pause').onclick=()=>{if(mode==='local'){if(audio.paused)audio.play().catch(()=>{status='musicBlocked';paint();});else audio.pause();}else if(player?.getPlayerState){if(player.getPlayerState()===1)player.pauseVideo();else player.playVideo();}};
 document.getElementById('radio-volume').oninput=e=>{audio.volume=Number(e.target.value)/100;player?.setVolume?.(Number(e.target.value));};
 document.getElementById('music-files').onchange=e=>{const files=Array.from(e.target.files||[]).filter(f=>/\.(mp3|ogg|wav|m4a)$/i.test(f.name));if(!files.length)return;player?.stopVideo?.();audio.pause();for(const url of localUrls)URL.revokeObjectURL(url);localFiles=files;localUrls=files.map(f=>URL.createObjectURL(f));localBag=[];localIndex=-1;mode='local';document.getElementById('radio-player-wrap').hidden=true;audio.hidden=false;document.getElementById('radio-link').hidden=true;nextLocal();};
 paint();
 }
 function paint(){if(!panel)return;panel.querySelectorAll('[data-radio-label]').forEach(el=>el.textContent=text(el.dataset.radioLabel));document.getElementById('radio-close').setAttribute('aria-label',text('close'));document.getElementById('radio-volume').setAttribute('aria-label',text('volume'));document.getElementById('radio-status').textContent=text(status);document.getElementById('radio-pause').textContent=text(playing?'pauseMusic':'resumeMusic');document.getElementById('radio-next').textContent=text(active>=0||localIndex>=0?'nextTrack':'shuffle');const name=mode==='local'?localFiles[localIndex]?.name:CafeData.tracks[active]?.title;document.getElementById('radio-track').textContent=name?`♫ ${name}`:'';}
 function loadApi(){if(globalThis.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{let done=false;const script=document.createElement('script');const timer=setTimeout(()=>fail(),15000);function fail(){if(done)return;done=true;clearTimeout(timer);script.remove();apiPromise=null;reject(Error('Player unavailable'));}globalThis.onYouTubeIframeAPIReady=()=>{if(done)return;done=true;clearTimeout(timer);resolve();};script.src='https://www.youtube.com/iframe_api';script.onerror=fail;document.head.appendChild(script);});return apiPromise;}
 async function nextOfficial(){mode='youtube';audio.pause();audio.hidden=true;document.getElementById('radio-player-wrap').hidden=false;status='musicLoading';paint();try{await loadApi();if(panel.hidden||mode!=='youtube')return;if(!bag.length)bag=shuffled(CafeData.tracks.length,active);active=bag.pop();const track=CafeData.tracks[active];const link=document.getElementById('radio-link');link.href='https://www.youtube.com/watch?v='+track.id;link.hidden=false;paint();if(player?.loadVideoById){player.loadVideoById(track.id);return;}
 const readyTimeout=setTimeout(()=>{if(status==='musicLoading'){status='musicError';paint();}},15000);
 player=new YT.Player('youtube-player',{width:340,height:220,host:'https://www.youtube-nocookie.com',videoId:track.id,playerVars:{playsinline:1,origin:location.origin,rel:0,controls:1},events:{onReady:e=>{clearTimeout(readyTimeout);e.target.setVolume(Number(document.getElementById('radio-volume').value));document.getElementById('radio-pause').disabled=false;if(panel.hidden||mode!=='youtube')return;status='musicReady';paint();e.target.playVideo();},onStateChange:e=>{if(mode!=='youtube')return;playing=e.data===1;if(e.data===0){nextOfficial();return;}if(e.data===1)status='musicPlaying';else if(e.data===2)status='musicPaused';paint();},onError:()=>{playing=false;status='musicError';paint();},onAutoplayBlocked:()=>{status='musicBlocked';paint();}}});
 }catch{playing=false;status='musicError';const track=CafeData.tracks[active<0?0:active],link=document.getElementById('radio-link');link.href='https://www.youtube.com/watch?v='+track.id;link.hidden=false;paint();}}
 function nextLocal(){if(!localFiles.length)return;if(!localBag.length)localBag=shuffled(localFiles.length,localIndex);localIndex=localBag.pop();audio.src=localUrls[localIndex];document.getElementById('radio-pause').disabled=false;audio.play().catch(()=>{status='musicBlocked';paint();});paint();}
 return {open(lang){language=lang;init();panel.hidden=false;paint();},setLanguage(lang){language=lang;paint();}};
})();
